sonar.projectKey=5g-small-cell-monitoring-agent
sonar.projectName=5G Small Cell Monitoring Agent
sonar.sources=src,include,scripts
sonar.tests=tests
sonar.cfamily.compile-commands=build/compile_commands.json
