sonar.projectKey=5g-small-cell-monitoring-agent
sonar.projectName=5G Small Cell Monitoring Agent
sonar.sources=src,include,scripts
sonar.tests=tests,test_cpp
sonar.sourceEncoding=UTF-8
sonar.cfamily.compile-commands=build/compile_commands.json
sonar.python.version=3.12
sonar.exclusions=build/**,**/*.html
